pr:
  branches:
    include:
      - dev
  paths:
    exclude:
      - docs/*
      - README.md

trigger:
 branches:
   include:
     - master
 paths:
   exclude:
     - docs/*
     - README.md
     - azure-pipelines-ci.yml
     - azure-pipelines-ci-cd.yml

stages:
- stage: Build_Stage
  displayName: Build Stage
  jobs:
  - job: WebApp
    displayName: Build Web App Job
    pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: 'windows-2019'
      demands: java
    variables:
      BuildConfiguration: release
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/WebApp.csproj'

    - powershell: |
       Write-Host "Hello World"
       $paths = Get-ChildItem -include *.csproj -Recurse
       foreach($pathobject in $paths) 
       {
           $path = $pathobject.fullname
           $doc = New-Object System.Xml.XmlDocument
           $doc.Load($path)
           $child = $doc.CreateElement("ProjectGuid")
           $child.InnerText = [guid]::NewGuid().ToString().ToUpper()
           $node = $doc.SelectSingleNode("//Project/PropertyGroup")
           $node.AppendChild($child)
           $doc.Save($path)
       }
      workingDirectory: WebApp
      displayName: 'PS : Add Project GUID'

    - task: SonarCloudPrepare@1
      displayName: Prepare analysis on SonarCloud
      inputs:
        SonarCloud: WebAppWithDatabaseDemo
        organization: dotnet-core-mvc-app
        projectKey: WebAppWithDatabaseDemoAbhay

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/WebApp.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*UnitTest*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: SonarCloudAnalyze@1
      displayName: Run Code Analysis

    - task: SonarCloudPublish@1
      displayName: Publish Quality Gate Result

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact (WebApp.zip)
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: drop

  - job: Database
    displayName: Build Database Job
    pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: 'windows-2019'
      demands: msbuild

    steps:
    - task: MSBuild@1
      displayName: Build solution WebApp.Database.sqlproj
      inputs:
        solution: WebApp.Database/WebApp.Database.sqlproj
        msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact (Dacpac)
      inputs:
        ArtifactName: dacpac

  - job: Selenium
    displayName: Build UI Tests Job
    pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: 'windows-2019'
      demands: msbuild

    steps:
    - task: NuGetToolInstaller@0
      displayName: Use NuGet 4.3.0

    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        restoreSolution: WebAppWithDatabase.sln

    - task: MSBuild@1
      displayName: Build project SeleniumUiTests.csproj
      inputs:
        solution: SeleniumUiTests/SeleniumUiTests.csproj
        msbuildArguments: '/p:OutDir=$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: UI-Test'
      inputs:
        ArtifactName: ui-tests

  - job: Infrastructure
    displayName: Publish Infra files Job
    pool:
      name: Hosted Ubuntu 1604
      vmImage: 'ubuntu-16.04'
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ARM templates'
      inputs:
        PathtoPublish: AzureResourceGroupDeployment
        ArtifactName: arm
  - job: InspecTest
    displayName: Publish Inspec test files Job
    pool:
      name: Hosted Ubuntu 1604
      vmImage: 'ubuntu-16.04'
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Inspec Azure Test'
      inputs:
        PathtoPublish: tunis-testing
        ArtifactName: inspectest

- stage: Dev_Stage
  displayName: Dev Stage
  dependsOn: Build_Stage
  jobs:
  - job: Dev
    displayName: Deploy to Dev Job
    pool:
      name: Hosted Windows 2019 with VS2019 
      vmImage: 'windows-2019'
    variables:
      Parameters.ConnectedServiceName: 'AzureServiceConnection' # couldn't be referenced
      ResourceGroupName: '$(Prefix)-$(Release.EnvironmentName)-$(UniqueId)-RG'
      Database.Admin: 'userabhay'
      Database.Password: '@Aa123456'
      Database.Name: 'EmployeesDB'
      WebAppName: '$(Prefix)-$(Release.EnvironmentName)-$(UniqueId)'
      WebAppNameUrl: 'https://$(WebAppName).azurewebsites.net/'
      SqlServerName: '$(Prefix)-sql-$(Release.EnvironmentName)-$(UniqueId)'
      Prefix: 'tunis-abhay'
      Release.EnvironmentName: 'dev'
      UniqueId: '1280' #'$(Build.BuildId)'

    steps:
    - checkout: none
    - task: UseRubyVersion@0
      displayName: "Install Ruby"
      inputs:
        versionSpec: ">= 2.5"
        addToPath: true
    - script: gem install inspec --no-doc
      displayName: "Install inspec"
    
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Artifacts
      inputs:
        artifactName: arm
        downloadPath: $(System.DefaultWorkingDirectory)

    - task: CmdLine@2
      inputs:
        script: 'ls'

    - task: AzureResourceGroupDeployment@2
      displayName: Validate ARM template
      enabled: 'true'
      inputs:
        azureSubscription: 'AzureServiceConnection'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(ResourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.parameters.json'
        overrideParameters: '-hostingPlanName "abhaydiwan-service-plan" -skuName "F1" -skuCapacity 1 -administratorLogin $(Database.Admin) -administratorLoginPassword $(Database.Password) -databaseName $(Database.Name) -collation "SQL_Latin1_General_CP1_CI_AS" -edition "Basic" -maxSizeBytes "1073741824" -requestedServiceObjectiveName "Basic" -webSiteName $(WebAppName) -sqlserverName $(SqlServerName)'
        deploymentMode: 'Validation'

    - task: AzureResourceGroupDeployment@2
      displayName: Create Or Update Resource Group
      enabled: 'true'
      inputs:
        azureSubscription: 'AzureServiceConnection'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(ResourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/**/arm/WebSiteSQLDatabase.parameters.json'
        overrideParameters: '-hostingPlanName "abhaydiwan-service-plan" -skuName "F1" -skuCapacity 1 -administratorLogin $(Database.Admin) -administratorLoginPassword $(Database.Password) -databaseName $(Database.Name) -collation "SQL_Latin1_General_CP1_CI_AS" -edition "Basic" -maxSizeBytes "1073741824" -requestedServiceObjectiveName "Basic" -webSiteName $(WebAppName) -sqlserverName $(SqlServerName)'
        deploymentMode: Complete

    - task: DownloadBuildArtifacts@0    
      displayName: Download WebApp.zip
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        itemPattern: '**/WebApp.zip'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: CmdLine@2
      inputs:
        script: |
          ls $(System.DefaultWorkingDirectory)

    - task: AzureRmWebAppDeployment@3
      displayName: Deploy Web App to Azure App Service
      enabled: 'true'
      inputs:
        azureSubscription: 'AzureServiceConnection'
        appType: 'webApp'
        WebAppName: '$(WebAppName)'
        TakeAppOfflineFlag: true
        JSONFiles: '**/appsettings.json'
        packageForLinux: '$(System.DefaultWorkingDirectory)/drop/WebApp.zip' #'$(System.ArtifactsDirectory)/**/drop/WebApp.zip'



    - task: DownloadBuildArtifacts@0    
      displayName: Download DacPac
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'dacpac'
        itemPattern: '**/*.dacpac'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: SqlAzureDacpacDeployment@1
      displayName: Azure SQL Publish DacPac to SQL Azure
      inputs:
        azureSubscription: 'AzureServiceConnection'
        ServerName: '$(SqlServerName).database.windows.net,1433'
        DatabaseName: '$(Database.Name)'
        SqlUsername: '$(Database.Admin)'
        SqlPassword: '$(Database.Password)'
        DacpacFile: '$(System.DefaultWorkingDirectory)/dacpac/WebApp.Database.dacpac'

    - task: DownloadBuildArtifacts@0    
      displayName: Download Selenium Tests
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'ui-tests'
        itemPattern: ''
        downloadPath: '$(System.DefaultWorkingDirectory)'


    - task: VSTest@2
      displayName: Selenium UI Tests
      inputs:
        testSelector: 'testAssemblies'
        searchFolder: '$(System.DefaultWorkingDirectory)/ui-tests'
        runSettingsFile: '$(System.DefaultWorkingDirectory)/ui-tests/.runsettings'
        overrideTestrunParameters: '-webAppUrl $(WebAppNameUrl)'
        testAssemblyVer2: |
          **\*Test*.dll 
          !**\*TestAdapter.dll 
          !**\obj\**
        runInParallel: false
        codeCoverageEnabled: false


- stage: Test_Stage
  displayName: Test Stage
  jobs:
  - job:
    displayName: Deploy to Test Job
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - task: UseRubyVersion@0
        displayName: "Install Ruby"
        inputs:
          versionSpec: ">= 2.5"
          addToPath: true
    
      - script: gem install inspec
        displayName: "Install inspec"
      - task: DownloadBuildArtifacts@0
        displayName: Download Build Artifacts
        inputs:
          artifactName: inspectest
          downloadPath: $(System.DefaultWorkingDirectory)    
  
      - task: Bash@3
        displayName: "Run inspec tests"
        inputs:
          targetType: inline
          script: |
            export AZURE_SUBSCRIPTION_ID="$(inspec.subscriptionId)"
            export AZURE_CLIENT_ID="$(inspec.clientId)"
            export AZURE_CLIENT_SECRET="$(inspec.clientSecret)"
            export AZURE_TENANT_ID="$(inspec.tenantId)"
            inspec exec . -t azure:// --reporter cli junit:testresults.xml html:report.html
    
      - task: PublishTestResults@2
        displayName: Publish inspec test results
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: "**/testresults.xml"
          mergeTestResults: true
    
      - task: PublishBuildArtifacts@1
        displayName: Publish inspec HTML report
        condition: succeededOrFailed()
        inputs:
          pathtoPublish: "report.html"
          artifactName: "report"
          
- stage: Prod_Stage
  displayName: Prod Stage
  jobs:
  - job:
    displayName: Deploy to Prod Job
    steps:
      - task: CmdLine@2
        inputs:
          script: 'ls'
